# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doca_grpc_orchestrator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='doca_grpc_orchestrator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x64oca_grpc_orchestrator.proto\"\x10\n\x0eProgramListReq\"$\n\x0bProgramList\x12\x15\n\rprogram_names\x18\x01 \x03(\t\";\n\x04\x41rgs\x12\x14\n\x0cprogram_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63mdline\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"\x12\n\x03Uid\x12\x0b\n\x03uid\x18\x01 \x01(\t\"-\n\x06Status\x12\x10\n\x08is_error\x18\x01 \x01(\x08\x12\x11\n\terror_msg\x18\x02 \x01(\t\"<\n\nRichStatus\x12\x11\n\x03uid\x18\x01 \x01(\x0b\x32\x04.Uid\x12\x1b\n\nerr_status\x18\x02 \x01(\x0b\x32\x07.Status2{\n\x10\x44ocaOrchestrator\x12/\n\x0eGetProgramList\x12\x0f.ProgramListReq\x1a\x0c.ProgramList\x12\x1c\n\x06\x43reate\x12\x05.Args\x1a\x0b.RichStatus\x12\x18\n\x07\x44\x65stroy\x12\x04.Uid\x1a\x07.Statusb\x06proto3'
)




_PROGRAMLISTREQ = _descriptor.Descriptor(
  name='ProgramListReq',
  full_name='ProgramListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=48,
)


_PROGRAMLIST = _descriptor.Descriptor(
  name='ProgramList',
  full_name='ProgramList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='program_names', full_name='ProgramList.program_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=86,
)


_ARGS = _descriptor.Descriptor(
  name='Args',
  full_name='Args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='program_name', full_name='Args.program_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmdline', full_name='Args.cmdline', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='Args.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=147,
)


_UID = _descriptor.Descriptor(
  name='Uid',
  full_name='Uid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Uid.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=167,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_error', full_name='Status.is_error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='Status.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=214,
)


_RICHSTATUS = _descriptor.Descriptor(
  name='RichStatus',
  full_name='RichStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='RichStatus.uid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_status', full_name='RichStatus.err_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=276,
)

_RICHSTATUS.fields_by_name['uid'].message_type = _UID
_RICHSTATUS.fields_by_name['err_status'].message_type = _STATUS
DESCRIPTOR.message_types_by_name['ProgramListReq'] = _PROGRAMLISTREQ
DESCRIPTOR.message_types_by_name['ProgramList'] = _PROGRAMLIST
DESCRIPTOR.message_types_by_name['Args'] = _ARGS
DESCRIPTOR.message_types_by_name['Uid'] = _UID
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['RichStatus'] = _RICHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramListReq = _reflection.GeneratedProtocolMessageType('ProgramListReq', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMLISTREQ,
  '__module__' : 'doca_grpc_orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:ProgramListReq)
  })
_sym_db.RegisterMessage(ProgramListReq)

ProgramList = _reflection.GeneratedProtocolMessageType('ProgramList', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMLIST,
  '__module__' : 'doca_grpc_orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:ProgramList)
  })
_sym_db.RegisterMessage(ProgramList)

Args = _reflection.GeneratedProtocolMessageType('Args', (_message.Message,), {
  'DESCRIPTOR' : _ARGS,
  '__module__' : 'doca_grpc_orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Args)
  })
_sym_db.RegisterMessage(Args)

Uid = _reflection.GeneratedProtocolMessageType('Uid', (_message.Message,), {
  'DESCRIPTOR' : _UID,
  '__module__' : 'doca_grpc_orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Uid)
  })
_sym_db.RegisterMessage(Uid)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'doca_grpc_orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

RichStatus = _reflection.GeneratedProtocolMessageType('RichStatus', (_message.Message,), {
  'DESCRIPTOR' : _RICHSTATUS,
  '__module__' : 'doca_grpc_orchestrator_pb2'
  # @@protoc_insertion_point(class_scope:RichStatus)
  })
_sym_db.RegisterMessage(RichStatus)



_DOCAORCHESTRATOR = _descriptor.ServiceDescriptor(
  name='DocaOrchestrator',
  full_name='DocaOrchestrator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=278,
  serialized_end=401,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProgramList',
    full_name='DocaOrchestrator.GetProgramList',
    index=0,
    containing_service=None,
    input_type=_PROGRAMLISTREQ,
    output_type=_PROGRAMLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='DocaOrchestrator.Create',
    index=1,
    containing_service=None,
    input_type=_ARGS,
    output_type=_RICHSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='DocaOrchestrator.Destroy',
    index=2,
    containing_service=None,
    input_type=_UID,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOCAORCHESTRATOR)

DESCRIPTOR.services_by_name['DocaOrchestrator'] = _DOCAORCHESTRATOR

# @@protoc_insertion_point(module_scope)
