#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated C config: don't edit
 */
#if (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,16))
#error compat requirement: Linux >= 2,6,16
#endif /* (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,16) */
#ifndef CONFIG_COMPAT_ISER_ATTR_IS_VISIBLE
#define CONFIG_COMPAT_ISER_ATTR_IS_VISIBLE 1
#endif /* CONFIG_COMPAT_ISER_ATTR_IS_VISIBLE */
#ifndef CONFIG_COMPAT_IF_ISCSI_SCSI_REQ
#define CONFIG_COMPAT_IF_ISCSI_SCSI_REQ 1
#endif /* CONFIG_COMPAT_IF_ISCSI_SCSI_REQ */
#ifndef CONFIG_COMPAT_SCSI_TARGET_UNBLOCK
#define CONFIG_COMPAT_SCSI_TARGET_UNBLOCK 1
#endif /* CONFIG_COMPAT_SCSI_TARGET_UNBLOCK */
#ifndef CONFIG_COMPAT_ETH_HW_ADDR_RANDOM
#define CONFIG_COMPAT_ETH_HW_ADDR_RANDOM 1
#endif /* CONFIG_COMPAT_ETH_HW_ADDR_RANDOM */
#ifndef CONFIG_COMPAT_NETDEV_FEATURES
#define CONFIG_COMPAT_NETDEV_FEATURES 1
#endif /* CONFIG_COMPAT_NETDEV_FEATURES */
#ifndef CONFIG_COMPAT_IS_WORK_BUSY
#define CONFIG_COMPAT_IS_WORK_BUSY 1
#endif /* CONFIG_COMPAT_IS_WORK_BUSY */
#ifndef CONFIG_COMPAT_IS_MAXRATE
#define CONFIG_COMPAT_IS_MAXRATE 1
#endif /* CONFIG_COMPAT_IS_MAXRATE */
#ifndef CONFIG_COMPAT_IS_QCN
#define CONFIG_COMPAT_IS_QCN 1
#endif /* CONFIG_COMPAT_IS_QCN */
#ifndef CONFIG_COMPAT_IS_REINIT_COMPLETION
#define CONFIG_COMPAT_IS_REINIT_COMPLETION 1
#endif /* CONFIG_COMPAT_IS_REINIT_COMPLETION */
#ifndef CONFIG_COMPAT_NETIF_IS_BOND_MASTER
#define CONFIG_COMPAT_NETIF_IS_BOND_MASTER 1
#endif /* CONFIG_COMPAT_NETIF_IS_BOND_MASTER */
#ifndef CONFIG_COMPAT_NETIF_IS_XPS
#define CONFIG_COMPAT_NETIF_IS_XPS 1
#endif /* CONFIG_COMPAT_NETIF_IS_XPS */
#ifndef CONFIG_COMPAT_NETIF_HAS_SET_XPS_QUEUE
#define CONFIG_COMPAT_NETIF_HAS_SET_XPS_QUEUE 1
#endif /* CONFIG_COMPAT_NETIF_HAS_SET_XPS_QUEUE */
#ifndef CONFIG_COMPAT_SOCK_HAS_QUEUE
#define CONFIG_COMPAT_SOCK_HAS_QUEUE 1
#endif /* CONFIG_COMPAT_SOCK_HAS_QUEUE */
#ifndef CONFIG_COMPAT_SKB_HAS_FRAG_LIST
#define CONFIG_COMPAT_SKB_HAS_FRAG_LIST 1
#endif /* CONFIG_COMPAT_SKB_HAS_FRAG_LIST */
#ifndef CONFIG_COMPAT_HAS_IRQ_AFFINITY_NOTIFIER
#define CONFIG_COMPAT_HAS_IRQ_AFFINITY_NOTIFIER 1
#endif /* CONFIG_COMPAT_HAS_IRQ_AFFINITY_NOTIFIER */
#ifndef CONFIG_COMPAT_NETIF_F_RXHASH
#define CONFIG_COMPAT_NETIF_F_RXHASH 1
#endif /* CONFIG_COMPAT_NETIF_F_RXHASH */
#ifndef CONFIG_COMPAT_IS_LINUX_CPU_RMAP
#define CONFIG_COMPAT_IS_LINUX_CPU_RMAP 1
#endif /* CONFIG_COMPAT_IS_LINUX_CPU_RMAP */
#ifndef CONFIG_COMPAT_RCU
#define CONFIG_COMPAT_RCU 1
#endif /* CONFIG_COMPAT_RCU */
#ifndef CONFIG_COMPAT_IS_KSTRTOX
#define CONFIG_COMPAT_IS_KSTRTOX 1
#endif /* CONFIG_COMPAT_IS_KSTRTOX */
#ifndef CONFIG_COMPAT_IS_IP_TOS2PRIO
#define CONFIG_COMPAT_IS_IP_TOS2PRIO 1
#endif /* CONFIG_COMPAT_IS_IP_TOS2PRIO */
#ifndef CONFIG_COMPAT_IS_BITOP
#define CONFIG_COMPAT_IS_BITOP 1
#endif /* CONFIG_COMPAT_IS_BITOP */
#ifndef CONFIG_COMPAT_DEV_UC_MC_ADD_CONST
#define CONFIG_COMPAT_DEV_UC_MC_ADD_CONST 1
#endif /* CONFIG_COMPAT_DEV_UC_MC_ADD_CONST */
#ifndef CONFIG_COMPAT_NDO_VF_MAC_VLAN
#define CONFIG_COMPAT_NDO_VF_MAC_VLAN 1
#endif /* CONFIG_COMPAT_NDO_VF_MAC_VLAN */
#ifndef CONFIG_COMPAT_IS_VF_INFO_SPOOFCHK
#define CONFIG_COMPAT_IS_VF_INFO_SPOOFCHK 1
#endif /* CONFIG_COMPAT_IS_VF_INFO_SPOOFCHK */
#ifndef CONFIG_COMPAT_IS_VF_INFO_LINKSTATE
#define CONFIG_COMPAT_IS_VF_INFO_LINKSTATE 1
#endif /* CONFIG_COMPAT_IS_VF_INFO_LINKSTATE */
#ifndef CONFIG_COMPAT_IS_PCI_PHYSFN
#define CONFIG_COMPAT_IS_PCI_PHYSFN 1
#endif /* CONFIG_COMPAT_IS_PCI_PHYSFN */
#ifndef CONFIG_COMPAT_XPRT_RESERVE_XPRT_CONG_2PARAMS
#define CONFIG_COMPAT_XPRT_RESERVE_XPRT_CONG_2PARAMS 1
#endif /* CONFIG_COMPAT_XPRT_RESERVE_XPRT_CONG_2PARAMS */
#ifndef CONFIG_COMPAT_RESERVE_XPRT_2PARAMS
#define CONFIG_COMPAT_RESERVE_XPRT_2PARAMS 1
#endif /* CONFIG_COMPAT_RESERVE_XPRT_2PARAMS */
#ifndef CONFIG_COMPAT_XPRT_ALLOC_4PARAMS
#define CONFIG_COMPAT_XPRT_ALLOC_4PARAMS 1
#endif /* CONFIG_COMPAT_XPRT_ALLOC_4PARAMS */
#ifndef CONFIG_COMPAT_XPRTRDMA_NEEDED
#define CONFIG_COMPAT_XPRTRDMA_NEEDED 1
#endif /* CONFIG_COMPAT_XPRTRDMA_NEEDED */
#ifndef CONFIG_COMPAT_VIRTQUEUE_GET_BUF
#define CONFIG_COMPAT_VIRTQUEUE_GET_BUF 1
#endif /* CONFIG_COMPAT_VIRTQUEUE_GET_BUF */
#ifndef CONFIG_COMPAT_VIRTQUEUE_KICK
#define CONFIG_COMPAT_VIRTQUEUE_KICK 1
#endif /* CONFIG_COMPAT_VIRTQUEUE_KICK */
#ifndef CONFIG_COMPAT_ZC_REQUEST
#define CONFIG_COMPAT_ZC_REQUEST 1
#endif /* CONFIG_COMPAT_ZC_REQUEST */
#ifndef CONFIG_COMPAT_GFP_T
#define CONFIG_COMPAT_GFP_T 1
#endif /* CONFIG_COMPAT_GFP_T */
#ifndef CONFIG_COMPAT_IS_BITMAP
#define CONFIG_COMPAT_IS_BITMAP 1
#endif /* CONFIG_COMPAT_IS_BITMAP */
#ifndef CONFIG_COMPAT_IS_BLKDEV_ISSUE_ZEROOUT_HAS_FLAGS
#define CONFIG_COMPAT_IS_BLKDEV_ISSUE_ZEROOUT_HAS_FLAGS 1
#endif /* CONFIG_COMPAT_IS_BLKDEV_ISSUE_ZEROOUT_HAS_FLAGS */
#ifndef CONFIG_COMPAT_IS_PRIO_TC_MAP
#define CONFIG_COMPAT_IS_PRIO_TC_MAP 1
#endif /* CONFIG_COMPAT_IS_PRIO_TC_MAP */
#ifndef CONFIG_IS_RX_HANDLER_RESULT
#define CONFIG_IS_RX_HANDLER_RESULT 1
#endif /* CONFIG_IS_RX_HANDLER_RESULT */
#ifndef CONFIG_IS_NDO_ADD_SLAVE
#define CONFIG_IS_NDO_ADD_SLAVE 1
#endif /* CONFIG_IS_NDO_ADD_SLAVE */
#ifndef CONFIG_MODULE_EEPROM_ETHTOOL
#define CONFIG_MODULE_EEPROM_ETHTOOL 1
#endif /* CONFIG_MODULE_EEPROM_ETHTOOL */
#ifndef CONFIG_TIMESTAMP_ETHTOOL
#define CONFIG_TIMESTAMP_ETHTOOL 1
#endif /* CONFIG_TIMESTAMP_ETHTOOL */
#ifndef CONFIG_COMPAT_INDIR_SETTING
#define CONFIG_COMPAT_INDIR_SETTING 1
#endif /* CONFIG_COMPAT_INDIR_SETTING */
#ifndef CONFIG_COMPAT_EN_SYSFS
#define CONFIG_COMPAT_EN_SYSFS 1
#endif /* CONFIG_COMPAT_EN_SYSFS */
#ifndef CONFIG_COMPAT_VXLAN_ENABLED
#define CONFIG_COMPAT_VXLAN_ENABLED 1
#endif /* CONFIG_COMPAT_VXLAN_ENABLED */
#ifndef CONFIG_COMPAT_IFLA_VF_LINK_STATE_MAX
#define CONFIG_COMPAT_IFLA_VF_LINK_STATE_MAX 1
#endif /* CONFIG_COMPAT_IFLA_VF_LINK_STATE_MAX */
#ifndef CONFIG_COMPAT_VLAN_EGRESS_VISIBLE
#define CONFIG_COMPAT_VLAN_EGRESS_VISIBLE 1
#endif /* CONFIG_COMPAT_VLAN_EGRESS_VISIBLE */
#ifndef CONFIG_GENETLINK_IS_LIST_HEAD
#define CONFIG_GENETLINK_IS_LIST_HEAD 1
#endif /* CONFIG_GENETLINK_IS_LIST_HEAD */
#ifndef CONFIG_COMPAT_SETNUMTCS_INT
#define CONFIG_COMPAT_SETNUMTCS_INT 1
#endif /* CONFIG_COMPAT_SETNUMTCS_INT */
#ifndef CONFIG_COMPAT_FDB_API_EXISTS
#define CONFIG_COMPAT_FDB_API_EXISTS 1
#endif /* CONFIG_COMPAT_FDB_API_EXISTS */
#ifndef CONFIG_COMPAT_FDB_ADD_NLATTR
#define CONFIG_COMPAT_FDB_ADD_NLATTR 1
#endif /* CONFIG_COMPAT_FDB_ADD_NLATTR */
#ifndef CONFIG_COMPAT_FDB_DEL_NLATTR
#define CONFIG_COMPAT_FDB_DEL_NLATTR 1
#endif /* CONFIG_COMPAT_FDB_DEL_NLATTR */
#ifndef CONFIG_COMPAT_FDB_CONST_ADDR
#define CONFIG_COMPAT_FDB_CONST_ADDR 1
#endif /* CONFIG_COMPAT_FDB_CONST_ADDR */
#ifndef CONFIG_COMPAT_FDB_U16_VID
#define CONFIG_COMPAT_FDB_U16_VID 1
#endif /* CONFIG_COMPAT_FDB_U16_VID */
#ifndef CONFIG_COMPAT_SELECT_QUEUE_FALLBACK
#define CONFIG_COMPAT_SELECT_QUEUE_FALLBACK 1
#endif /* CONFIG_COMPAT_SELECT_QUEUE_FALLBACK */
#ifndef CONFIG_COMPAT_PTP_CLOCK
#define CONFIG_COMPAT_PTP_CLOCK 1
#endif /* CONFIG_COMPAT_PTP_CLOCK */
#ifndef CONFIG_COMPAT_PTP_N_PINS
#define CONFIG_COMPAT_PTP_N_PINS 1
#endif /* CONFIG_COMPAT_PTP_N_PINS */
#ifndef CONFIG_COMPAT_PTP_CLOCK_REGISTER
#define CONFIG_COMPAT_PTP_CLOCK_REGISTER 1
#endif /* CONFIG_COMPAT_PTP_CLOCK_REGISTER */
#ifndef CONFIG_COMPAT_THIS_MODULE
#define CONFIG_COMPAT_THIS_MODULE 1
#endif /* CONFIG_COMPAT_THIS_MODULE */
#ifndef CONFIG_COMPAT_ISCSI_SESSION_FRWD_LOCK
#define CONFIG_COMPAT_ISCSI_SESSION_FRWD_LOCK 1
#endif /* CONFIG_COMPAT_ISCSI_SESSION_FRWD_LOCK */
#ifndef CONFIG_COMPAT_IS_VF_INFO_MAX_TX_RATE
#define CONFIG_COMPAT_IS_VF_INFO_MAX_TX_RATE 1
#endif /* CONFIG_COMPAT_IS_VF_INFO_MAX_TX_RATE */
#ifndef CONFIG_COMPAT_NET_DEVICE_IS_NUM_TC
#define CONFIG_COMPAT_NET_DEVICE_IS_NUM_TC 1
#endif /* CONFIG_COMPAT_NET_DEVICE_IS_NUM_TC */
#ifndef CONFIG_COMPAT_IS_FILTER_DEV
#define CONFIG_COMPAT_IS_FILTER_DEV 1
#endif /* CONFIG_COMPAT_IS_FILTER_DEV */
#ifndef CONFIG_COMPAT_IS_INT_SETAPP
#define CONFIG_COMPAT_IS_INT_SETAPP 1
#endif /* CONFIG_COMPAT_IS_INT_SETAPP */
#ifndef CONFIG_COMPAT_IS_ENUM_PCIE_LINK_WIDTH
#define CONFIG_COMPAT_IS_ENUM_PCIE_LINK_WIDTH 1
#endif /* CONFIG_COMPAT_IS_ENUM_PCIE_LINK_WIDTH */
#ifndef CONFIG_COMPAT_SVC_XPRT_OPS_XPO_SECURE_PORT
#define CONFIG_COMPAT_SVC_XPRT_OPS_XPO_SECURE_PORT 1
#endif /* CONFIG_COMPAT_SVC_XPRT_OPS_XPO_SECURE_PORT */
#ifndef CONFIG_COMPAT_IS_SVC_XPRT_CLASS_XCL_IDENT
#define CONFIG_COMPAT_IS_SVC_XPRT_CLASS_XCL_IDENT 1
#endif /* CONFIG_COMPAT_IS_SVC_XPRT_CLASS_XCL_IDENT */
#ifndef CONFIG_COMPAT_IS_XPRT_CREATE_NET
#define CONFIG_COMPAT_IS_XPRT_CREATE_NET 1
#endif /* CONFIG_COMPAT_IS_XPRT_CREATE_NET */
#ifndef CONFIG_COMPAT_IS_RPC_RQST_RQ_XMIT_BYTES_SENT
#define CONFIG_COMPAT_IS_RPC_RQST_RQ_XMIT_BYTES_SENT 1
#endif /* CONFIG_COMPAT_IS_RPC_RQST_RQ_XMIT_BYTES_SENT */
#ifndef CONFIG_COMPAT_IS_SUNRPC_ADDR_H
#define CONFIG_COMPAT_IS_SUNRPC_ADDR_H 1
#endif /* CONFIG_COMPAT_IS_SUNRPC_ADDR_H */
#ifndef CONFIG_COMPAT_IS_INET_SOCK_INET_NUM
#define CONFIG_COMPAT_IS_INET_SOCK_INET_NUM 1
#endif /* CONFIG_COMPAT_IS_INET_SOCK_INET_NUM */
#ifndef CONFIG_COMPAT_IS_SOCK_SK_WQ
#define CONFIG_COMPAT_IS_SOCK_SK_WQ 1
#endif /* CONFIG_COMPAT_IS_SOCK_SK_WQ */
#ifndef CONFIG_COMPAT_IS_NETDEV_DQL
#define CONFIG_COMPAT_IS_NETDEV_DQL 1
#endif /* CONFIG_COMPAT_IS_NETDEV_DQL */
#ifndef CONFIG_COMPAT_IS_GET_TUNABLE
#define CONFIG_COMPAT_IS_GET_TUNABLE 1
#endif /* CONFIG_COMPAT_IS_GET_TUNABLE */
#ifndef CONFIG_COMPAT_SCSI_TRANSFER_LENGTH
#define CONFIG_COMPAT_SCSI_TRANSFER_LENGTH 1
#endif /* CONFIG_COMPAT_SCSI_TRANSFER_LENGTH */
#ifndef CONFIG_COMPAT_IS_SMP_MB__AFTER_ATOMIC
#define CONFIG_COMPAT_IS_SMP_MB__AFTER_ATOMIC 1
#endif /* CONFIG_COMPAT_IS_SMP_MB__AFTER_ATOMIC */
#ifndef CONFIG_COMPAT_ISCSIT_WAIT_CONN
#define CONFIG_COMPAT_ISCSIT_WAIT_CONN 1
#endif /* CONFIG_COMPAT_ISCSIT_WAIT_CONN */
#ifndef CONFIG_COMPAT_ISCSIT_ABORTED_TASK
#define CONFIG_COMPAT_ISCSIT_ABORTED_TASK 1
#endif /* CONFIG_COMPAT_ISCSIT_ABORTED_TASK */
#ifndef CONFIG_COMPAT_ISCSIT_GET_SUP_PROT_OPS
#define CONFIG_COMPAT_ISCSIT_GET_SUP_PROT_OPS 1
#endif /* CONFIG_COMPAT_ISCSIT_GET_SUP_PROT_OPS */
#ifndef CONFIG_COMPAT_ISCSIT_PRIV_CMD
#define CONFIG_COMPAT_ISCSIT_PRIV_CMD 1
#endif /* CONFIG_COMPAT_ISCSIT_PRIV_CMD */
#ifndef CONFIG_COMPAT_IS_FILE_INODE
#define CONFIG_COMPAT_IS_FILE_INODE 1
#endif /* CONFIG_COMPAT_IS_FILE_INODE */
#ifndef CONFIG_COMPAT_IS_THIS_CPU_PTR
#define CONFIG_COMPAT_IS_THIS_CPU_PTR 1
#endif /* CONFIG_COMPAT_IS_THIS_CPU_PTR */
#ifndef CONFIG_COMPAT_IS_CONST_PCI_ERROR_HANDLERS
#define CONFIG_COMPAT_IS_CONST_PCI_ERROR_HANDLERS 1
#endif /* CONFIG_COMPAT_IS_CONST_PCI_ERROR_HANDLERS */
#ifndef CONFIG_COMPAT_IS_DCBNL_OPS_CONST
#define CONFIG_COMPAT_IS_DCBNL_OPS_CONST 1
#endif /* CONFIG_COMPAT_IS_DCBNL_OPS_CONST */
#ifndef CONFIG_COMPAT_HMM_RANGE_FAULT_RETURNS_INT
#define CONFIG_COMPAT_HMM_RANGE_FAULT_RETURNS_INT 1
#endif /* CONFIG_COMPAT_HMM_RANGE_FAULT_RETURNS_INT */
#ifndef CONFIG_COMPAT_TC_PRIO_IS_MAJOR
#define CONFIG_COMPAT_TC_PRIO_IS_MAJOR 1
#endif /* CONFIG_COMPAT_TC_PRIO_IS_MAJOR */
#ifndef CONFIG_COMPAT_KERNEL_CT
#define CONFIG_COMPAT_KERNEL_CT 1
#endif /* CONFIG_COMPAT_KERNEL_CT */
#endif /* COMPAT_AUTOCONF_INCLUDED */
