/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define RTE_ARCH armv8

#undef RTE_ARCH_32

#define RTE_ARCH_64

#define RTE_ARCH_ARM 1

#define RTE_ARCH_ARM64

#undef RTE_ARCH_ARM64_MEMCPY

#undef RTE_ARM_USE_WFE

#define RTE_BUS_AUXILIARY 1

#define RTE_BUS_PCI 1

#define RTE_BUS_VDEV 1

#define RTE_CACHE_LINE_SIZE 64

#define RTE_COMMON_MLX5 1

#define RTE_COMMON_QAT 1

#define RTE_COMPILE_TIME_CPUFLAGS RTE_CPUFLAG_NEON,RTE_CPUFLAG_CRC32

#define RTE_CRYPTO_MLX5 1

#define RTE_DRIVER_MEMPOOL_BUCKET_SIZE_KB 64

#define RTE_EAL_PMD_PATH ""

#define RTE_EAL_VFIO

#undef RTE_ENABLE_TRACE_FP

#define RTE_ENV_FREEBSD 0

#define RTE_ENV_LINUX 1

#define RTE_ENV_WINDOWS 2

#define RTE_EXEC_ENV 1

#define RTE_EXEC_ENV_IS_FREEBSD 0

#define RTE_EXEC_ENV_IS_LINUX 1

#define RTE_EXEC_ENV_IS_WINDOWS 0

#define RTE_EXEC_ENV_LINUX 1

#define RTE_FORCE_INTRINSICS 1

#define RTE_HAS_JANSSON 1

#define RTE_HAS_LIBNUMA 1

#define RTE_HAS_LIBPCAP 1

#define RTE_HAS_OPENSSL 1

#define RTE_IOVA_AS_PA 1

#undef RTE_LIBEAL_USE_HPET

#define RTE_LIBRTE_DPAA2_USE_PHYS_IOVA

#define RTE_LIBRTE_VHOST_POSTCOPY

#define RTE_LIB_CMDLINE 1

#define RTE_LIB_COMPRESSDEV 1

#define RTE_LIB_CRYPTODEV 1

#define RTE_LIB_DMADEV 1

#define RTE_LIB_EAL 1

#define RTE_LIB_ETHDEV 1

#define RTE_LIB_HASH 1

#define RTE_LIB_KVARGS 1

#define RTE_LIB_MBUF 1

#define RTE_LIB_MEMPOOL 1

#define RTE_LIB_METER 1

#define RTE_LIB_NET 1

#define RTE_LIB_PCI 1

#define RTE_LIB_POWER 1

#define RTE_LIB_RCU 1

#define RTE_LIB_REORDER 1

#define RTE_LIB_RING 1

#define RTE_LIB_SECURITY 1

#define RTE_LIB_TELEMETRY 1

#define RTE_LIB_TIMER 1

#define RTE_LIB_VHOST 1

#define RTE_MACHINE "armv8a"

#define RTE_MAX_ETHPORTS 32

#define RTE_MAX_LCORE 16

#define RTE_MAX_MEM_MB 524288

#define RTE_MAX_NUMA_NODES 1

#define RTE_MAX_VFIO_GROUPS 64

#define RTE_MBUF_REFCNT_ATOMIC

#define RTE_MEMPOOL_RING 1

#define RTE_TOOLCHAIN "gcc"

#define RTE_TOOLCHAIN_GCC 1

#define RTE_USE_C11_MEM_MODEL

#define RTE_USE_LIBBSD 1

#define RTE_VER_MINOR 1

#define RTE_VER_MONTH 11

#define RTE_VER_RELEASE 99

#define RTE_VER_SUFFIX ""

#define RTE_VER_YEAR 22

